#ifndef FOC_OPEN_H
#define FOC_OPEN_H

#include <motor/foc_common.h>

struct open_loop_foc_t {
    // Electrical angle generated by the open-loop controller.
    float angle = 0.0f;
    // Current commanded SVPWM modulation, Vref / Vbus
    float modulation = 0.0f;
    // Current commanded electrical frequency [Hz]
    float electrical_frequency = 0.0f;
    // Open-loop update rate [Hz].
    // Should match the TIM1 update ISR rate.
    float update_frequency = 20'000.0f;   // Hz
    // Ramp configuration
    float modulation_start = 0.10f;
    float modulation_end   = 0.25f;
    float frequency_start = 2.0f;
    float frequency_end   = 20.0f;
    // Ramp duration [s].
    float ramp_duration_s = 8.0f;
};

inline svpwm_t g_svpwm;
inline open_loop_foc_t g_open_loop;

inline void open_loop_update() {
    float angle = g_open_loop.angle;
    float alpha = g_open_loop.modulation * cosf(angle);
    float beta = g_open_loop.modulation * sinf(angle);
    svpwm_update(g_svpwm, alpha, beta);
    // open-loop owns angle advancement.
    float angle_step =
        TWO_PI *
        g_open_loop.electrical_frequency /
        g_open_loop.update_frequency;
    g_open_loop.angle += angle_step;
    if (g_open_loop.angle >= TWO_PI) {
        g_open_loop.angle -= TWO_PI;
    }
}

inline void tim1_callback_open(timer_event_t event) {
    if (event == TIMER_EVENT_UPDATE) {
        open_loop_update();
    }
}

inline void test_foc_open_loop() {
    timer_config_t tm{};
    tm.instance = TIM1;
    tm.interrupt_callback = tim1_callback_open;
    tm.mode = cms::ca1;
    timer_init(&tm);
    timer_set_frequency(&tm, 20000);
    static const uint8_t hs[] = {8, 9, 10};
    static const uint8_t ls[] = {13, 14, 15};
    timer_init_gpio(GPIOA, hs, 3, 1);
    timer_init_gpio(GPIOB, ls, 3, 1);
    //timer_set_dead_time(&tm, 250);
    timer_init_channel(&tm, 1, GPIOA, 8, GPIOB, 13);
    timer_init_channel(&tm, 2, GPIOA, 9, GPIOB, 14);
    timer_init_channel(&tm, 3, GPIOA, 10, GPIOB, 15);
    // start timer channels
    timer_start_channel(&tm, 1, true);
    timer_start_channel(&tm, 2, true);
    timer_start_channel(&tm, 3, true);

    g_svpwm.timer = &tm;
    g_open_loop.angle = 0.0f;
    g_open_loop.modulation = g_open_loop.modulation_start;
    g_open_loop.electrical_frequency = g_open_loop.frequency_start;
    const uint32_t ramp_start_ms = mcl::time_ms();
    uint32_t last_ramp_update_ms = ramp_start_ms;

    timer_enable_interrupt(&tm);
    timer_start(&tm);

    while (!getInstance<config>()->shouldExit()) {
        // TIM1 update interrupt and SysTick can wake the processor.
        __WFI();
        uint32_t now_ms = mcl::time_ms();
        // The ramp itself is very slow compared with the 20 kHz
        // PWM interrupt, so a 1 ms foreground update is sufficient.
        if ((uint32_t)(now_ms - last_ramp_update_ms) >= 1U) {
            float elapsed_s = (float)(now_ms - ramp_start_ms) * 0.001f;
            // Both values use EXACTLY the same elapsed_s.
            // Therefore the voltage and frequency ramps are
            // synchronized.
            g_open_loop.modulation =
                ramp_value(
                    g_open_loop.modulation_start,
                    g_open_loop.modulation_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            g_open_loop.electrical_frequency =
                ramp_value(
                    g_open_loop.frequency_start,
                    g_open_loop.frequency_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            last_ramp_update_ms = now_ms;
        }
        static uint32_t last_log_ms = 0;
        if ((uint32_t)(now_ms - last_log_ms) >= 10U) {
            LOG << " modulation: " << g_open_loop.modulation
                    << ", electrical_frequency " << g_open_loop.electrical_frequency;
            last_log_ms = now_ms;
        }
    }
    timer_stop(&tm);
}

#endif