#ifndef VF_DRIVE_H
#define VF_DRIVE_H

#include <foc/svpwm.h>
#include <foc/encoder.h>

struct open_loop_t {
    // Electrical angle generated by the open-loop controller.
    float angle = 0.0f;
    // Current commanded SVPWM modulation, Vref / Vbus
    float modulation = 0.0f;
    // Current commanded electrical frequency [Hz]
    float electrical_frequency = 0.0f;
    // Open-loop update rate [Hz].
    // Should match the TIM1 update ISR rate.
    float update_frequency = 20'000.0f;   // Hz
    // Ramp configuration
    float modulation_start = 0.2f;
    float modulation_end   = 0.2f;
    // 0.05f ultra slow works but with some jitter
    // 0.1f works with little jitter
    // 0.5f is butter smooth
    float frequency_start = 0.5f;
    float frequency_end   = 0.5f;
    // Ramp duration [s].
    float ramp_duration_s = 30.0f;
};

inline svpwm_t g_svpwm;
inline open_loop_t g_open_loop;
inline volatile bool encoder_hold = true;

inline void open_loop_update() {
    float angle = g_open_loop.angle;
    float alpha = g_open_loop.modulation * cosf(angle);
    float beta = g_open_loop.modulation * sinf(angle);
    svpwm_update(g_svpwm, alpha, beta);
    // advance the angle based on commanded electrical frequency
    float angle_step = TWO_PI * g_open_loop.electrical_frequency /
        g_open_loop.update_frequency;
    g_open_loop.angle += angle_step;
    if (g_open_loop.angle >= TWO_PI) {
        g_open_loop.angle -= TWO_PI;
    }
}

inline void tim1_callback_open(timer_event_t event) {
    if (!encoder_hold && event == TIMER_EVENT_UPDATE) {
        open_loop_update();
    }
}

serial::i2c *i2c_bus = nullptr;
void tim2_encoder_vfd_callback(timer_event_t event) {
    if (event == TIMER_EVENT_UPDATE) {
        // executes at 1kHz
        encoder_read_and_update_angles(*i2c_bus);
    }
}

inline void test_vf_drive() {
    timer_config_t tm{};
    tm.instance = TIM1;
    tm.interrupt_callback = tim1_callback_open;
    tm.mode = cms::ca1;
    timer_init(&tm);
    timer_set_frequency(&tm, 20000);
    static const uint8_t hs[] = {8, 9, 10};
    static const uint8_t ls[] = {13, 14, 15};
    timer_init_gpio(GPIOA, hs, 3, 1);
    timer_init_gpio(GPIOB, ls, 3, 1);
    //timer_set_dead_time(&tm, 250);
    timer_init_channel(&tm, 1, GPIOA, 8, GPIOB, 13);
    timer_init_channel(&tm, 2, GPIOA, 9, GPIOB, 14);
    timer_init_channel(&tm, 3, GPIOA, 10, GPIOB, 15);
    // start timer channels
    timer_start_channel(&tm, 1, true);
    timer_start_channel(&tm, 2, true);
    timer_start_channel(&tm, 3, true);

    g_svpwm.timer = &tm;
    g_open_loop.angle = 0.0f;
    g_open_loop.modulation = g_open_loop.modulation_start;
    g_open_loop.electrical_frequency = g_open_loop.frequency_start;

    timer_enable_interrupt(&tm);
    encoder_hold = true;
    timer_start(&tm);

    // Encoder bus
    serial::i2c bus(3, 10, 400'000, I2C2, GPIOB);
    svpwm_t calibration_svm{};
    calibration_svm.timer = &tm;
    auto rc = calibrate_encoder(bus, calibration_svm, 9.49f);
    if (!rc) return;
    // Read the encoder at the final calibrated rotor position.
    encoder_read_and_update_angles(bus);
    // Start the open-loop electrical field from the
    // same electrical angle as the encoder.
    g_open_loop.angle = encoder_read->electrical_angle;
    // Discard any velocity-estimator state accumulated during calibration.
    reset_velocity_estimator();

    // TIM2 encoder read setup
    i2c_bus = &bus;
    timer_config_t tim2_cfg = {};
    tim2_cfg.instance = TIM2;
    tim2_cfg.mode = cms::ea;
    tim2_cfg.interrupt_callback = tim2_encoder_vfd_callback;
    // Configure TIM2 and make its counter clock 1 MHz
    timer_init(&tim2_cfg);
    // Configure update frequency = 1kHz
    timer_set_frequency(&tim2_cfg, 1000);
    // Register/enable TIM2 update interrupt
    timer_enable_interrupt(&tim2_cfg);
    // Start TIM2
    timer_start(&tim2_cfg);

    const uint32_t ramp_start_ms = mcl::time_ms();
    uint32_t last_ramp_update_ms = ramp_start_ms;
    // Now allow TIM1 to advance the open-loop field.
    encoder_hold = false;

    while (true) {
        uint32_t now_ms = mcl::time_ms();
        // 1 ms foreground ramp update
        if ((uint32_t)(now_ms - last_ramp_update_ms) >= 1U) {
            float elapsed_s = (float)(now_ms - ramp_start_ms) * 0.001f;
            // voltage and frequency ramps are synchronized
            // since both use the same elapsed_s
            g_open_loop.modulation =
                ramp_linear(
                    g_open_loop.modulation_start,
                    g_open_loop.modulation_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            g_open_loop.electrical_frequency =
                ramp_linear(
                    g_open_loop.frequency_start,
                    g_open_loop.frequency_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            last_ramp_update_ms = now_ms;
        }
        static uint32_t last_log_ms = 0;
        if ((uint32_t)(now_ms - last_log_ms) >= 500U) {
            float phase_error =
                g_open_loop.angle - encoder_read->electrical_angle;
            // wrap phase error to [-PI, PI].
            if (phase_error > PI)
                phase_error -= TWO_PI;
            else if (phase_error < -PI)
                phase_error += TWO_PI;
            LOG << "mod: " << g_open_loop.modulation
                << " cmd_ef: " << g_open_loop.electrical_frequency
                << " cmd_ea: " << g_open_loop.angle
                << " enc_ea: " << encoder_read->electrical_angle
                << " ph_err: " << phase_error
                << " ma: " << encoder_read->mechanical_angle
                << " wm: " << encoder_read->mechanical_velocity
                << " we: " << encoder_read->electrical_velocity;
            last_log_ms = now_ms;
        }
    }
    timer_stop(&tm);
}

#endif