#ifndef VF_DRIVE_H
#define VF_DRIVE_H

#include <foc/hardware.h>
#include <foc/svpwm.h>
#include <foc/encoder.h>

struct vf_controller_t {

    hardware_t hw{};
    encoder_t encoder;

    enum vf_state { stopped, running, fault };
    vf_state state = vf_state::stopped;

    // Electrical angle generated by the open-loop controller.
    float angle = 0.0f;
    // Commanded SVPWM modulation, Vref / Vbus.
    float modulation = 0.0f;
    // Commanded electrical frequency [Hz].
    float electrical_frequency = 0.0f;
    // Open-loop update rate [Hz].
    // Must match the TIM1 update ISR rate.
    float update_frequency = 20'000.0f;
    // Ramp configuration
    float modulation_start = 0.2f;
    float modulation_end   = 0.2f;
    // 0.05f ultra slow works but with some jitter
    // 0.1f works with little jitter
    // 0.5f is butter smooth
    float frequency_start = 0.5f;
    float frequency_end   = 0.5f;
    // Ramp duration [s].
    float ramp_duration_s = 30.0f;

    // TIM1 PWM callback trampoline
    static void pwm_trampoline(timer_event_t event, void *ctx) {
        if (ctx) {
            ((vf_controller_t *)ctx)->pwm_callback(event);
        }
    }
    // TIM2 encoder callback trampoline
    static void encoder_trampoline(timer_event_t event, void *ctx) {
        if (ctx) {
            ((vf_controller_t *)ctx)->encoder_callback(event);
        }
    }
    // TIM1 PWM callback
    void pwm_callback(timer_event_t event) {
        if (event == TIMER_EVENT_UPDATE &&
                state == vf_state::running) {
            open_loop_update();
        }
    }
    // TIM2 encoder callback
    void encoder_callback(timer_event_t event) {
        if (event == TIMER_EVENT_UPDATE) {
            // Executes at 1 kHz.
            encoder.update();
        }
    }
    // Open-loop V/F update
    // Runs from the TIM1 update ISR at 20 kHz.
    void open_loop_update() {
        const float current_angle = angle;
        const float alpha = modulation * cosf(current_angle);
        const float beta = modulation * sinf(current_angle);
        // modulation is already normalized to Vbus.
        voltage_to_timer_pwm(&hw.pwm_timer, alpha, beta);
        // Advance electrical angle according to
        // commanded electrical frequency.
        const float angle_step = TWO_PI * electrical_frequency / update_frequency;
        angle += angle_step;
        // Keep angle in [0, TWO_PI).
        if (angle >= TWO_PI) {
            angle -= TWO_PI;
        } else if (angle < 0.0f) {
            angle += TWO_PI;
        }
    }

    inline float ramp_linear(float start, float end, float elapsed_s) {
            if (ramp_duration_s <= 0.0f) {
                return end;
            } else {
                float frac = elapsed_s / ramp_duration_s;
                if (frac <= 0.0f)
                    frac = 0.0f;
                else if (frac >= 1.0f)
                    frac = 1.0f;
                return start +
                    frac * (end - start);
            }
    }

    void start() {
        state = vf_state::stopped;
        // TIM1 CH1/CH2/CH3 SVPWM setup
        hw.initialize_phase_pwm_timer(&pwm_trampoline, this);
        // Initialize open-loop state
        angle = 0.0f;
        modulation = modulation_start;
        electrical_frequency = frequency_start;
        // Start TIM1.
        // The PWM timer must be running during encoder
        // calibration because the calibration routine uses it.
        timer_enable_interrupt(&hw.pwm_timer);
        timer_start(&hw.pwm_timer);
        // Encoder calibration
        encoder.calibrate_sign_and_offset(&hw.pwm_timer);
        // Start velocity estimation from a clean state.
        encoder.reset_velocity();
        // Read encoder at the final calibrated rotor position.
        encoder.update();
        // Synchronize open-loop field with rotor.
        // This prevents an initial electrical-angle jump when
        // open-loop operation starts.
        const auto& enc = encoder.read();
        angle = enc.electrical_angle;
        // TIM2 encoder read setup
        hw.initialize_encoder_timer(&encoder_trampoline, this);
        // Ramp timing
        const uint32_t ramp_start_ms = mcl::time_ms();
        uint32_t last_ramp_update_ms = ramp_start_ms;
        uint32_t last_log_ms = ramp_start_ms;
        // Enable V/F operation. TIM1 ISR will now
        // begin advancing the electrical field.
        state = vf_state::running;

        // Foreground control loop
        while (!exit_vfd()) {
            const uint32_t now_ms = mcl::time_ms();
            if ((uint32_t)(now_ms - last_ramp_update_ms) >= 1U) {
                const float elapsed_s = (float)(now_ms - ramp_start_ms) * 0.001f;
                // Voltage and frequency use the same elapsed time,
                // therefore their ramps remain synchronized.
                modulation = ramp_linear(
                    modulation_start, modulation_end, elapsed_s);
                electrical_frequency = ramp_linear(
                    frequency_start, frequency_end, elapsed_s);
                last_ramp_update_ms = now_ms;
            }
            if ((uint32_t)(now_ms - last_log_ms) >= 500U) {
                log_vf_state();
                last_log_ms = now_ms;
            }
        }
    }

    void stop() {
        state = vf_state::stopped;
        timer_stop(&hw.pwm_timer);
    }

    bool exit_vfd() {
        if (state == vf_state::stopped) {
            return true;
        }
        if (getInstance<config>()->shouldExit()) {
            stop();
            return true;
        }
        return false;
    }

    inline void log_vf_state() {
        // Snapshot encoder state.
        const auto& enc = encoder.read();
        // Electrical phase error:
        // commanded open-loop angle-
        // encoder electrical angle
        float phase_error = angle - enc.electrical_angle;
        // Wrap phase error to [-PI, PI].
        if (phase_error > PI) {
            phase_error -= TWO_PI;
        } else if (phase_error < -PI) {
            phase_error += TWO_PI;
        }
        char log_buffer[512];
        int len = snprintf(log_buffer, sizeof(log_buffer),
            "cmd_mod:%f cmd_ef:%f cmd_ea:%f enc_ea:%f ph_err:%f ma:%f wm:%f we:%f",
                modulation, electrical_frequency, angle, enc.electrical_angle, phase_error,
                    enc.mechanical_angle, enc.mechanical_velocity, enc.electrical_velocity
        );
        if (len > 0) {
            if (len >= sizeof(log_buffer)) {
                len = sizeof(log_buffer) - 1;
            }
            LOG << std::string(log_buffer, len);
        }
    }

    void set_config(const KeyValue& kv) {

    }
};

vf_controller_t vf;

inline void test_vf_drive() {
    vf = {};
    mcl::config_callback =
        [](const command& cmd){
            if (cmd.type == command::command_type::kv) {
                vf.set_config(cmd.kv);
            } else if (cmd.type == command::command_type::action) {
                if (cmd.action == "stop") {
                    vf.stop();
                } else {
                    LOG << "invalid action";
                }
            } else {
                LOG << "invalid cmd type";
            }
        };
    vf.start();
}


#endif