#ifndef VF_DRIVE_H
#define VF_DRIVE_H

#include <foc/svpwm.h>
#include <foc/encoder.h>

struct open_loop_t {
    // Electrical angle generated by the open-loop controller.
    float angle = 0.0f;
    // Current commanded SVPWM modulation, Vref / Vbus
    float modulation = 0.0f;
    // Current commanded electrical frequency [Hz]
    float electrical_frequency = 0.0f;
    // Open-loop update rate [Hz].
    // Should match the TIM1 update ISR rate.
    float update_frequency = 20'000.0f;   // Hz
    // Ramp configuration
    float modulation_start = 0.15f;
    float modulation_end   = 0.15f;
    float frequency_start = 1.0f;
    float frequency_end   = 1.0f;
    // Ramp duration [s].
    float ramp_duration_s = 30.0f;
};

inline svpwm_t g_svpwm;
inline open_loop_t g_open_loop;
inline volatile bool encoder_hold = true;

inline void open_loop_update() {
    float angle = g_open_loop.angle;
    float alpha = g_open_loop.modulation * cosf(angle);
    float beta = g_open_loop.modulation * sinf(angle);
    svpwm_update(g_svpwm, alpha, beta);
    // open-loop owns angle advancement.
    float angle_step = TWO_PI * g_open_loop.electrical_frequency /
        g_open_loop.update_frequency;
    g_open_loop.angle += angle_step;
    if (g_open_loop.angle >= TWO_PI) {
        g_open_loop.angle -= TWO_PI;
    }
}

inline void tim1_callback_open(timer_event_t event) {
    if (!encoder_hold && event == TIMER_EVENT_UPDATE) {
        open_loop_update();
    }
}

inline void test_vf_drive() {
    timer_config_t tm{};
    tm.instance = TIM1;
    tm.interrupt_callback = tim1_callback_open;
    tm.mode = cms::ca1;
    timer_init(&tm);
    timer_set_frequency(&tm, 20000);
    static const uint8_t hs[] = {8, 9, 10};
    static const uint8_t ls[] = {13, 14, 15};
    timer_init_gpio(GPIOA, hs, 3, 1);
    timer_init_gpio(GPIOB, ls, 3, 1);
    //timer_set_dead_time(&tm, 250);
    timer_init_channel(&tm, 1, GPIOA, 8, GPIOB, 13);
    timer_init_channel(&tm, 2, GPIOA, 9, GPIOB, 14);
    timer_init_channel(&tm, 3, GPIOA, 10, GPIOB, 15);
    // start timer channels
    timer_start_channel(&tm, 1, true);
    timer_start_channel(&tm, 2, true);
    timer_start_channel(&tm, 3, true);

    g_svpwm.timer = &tm;
    g_open_loop.angle = 0.0f;
    g_open_loop.modulation = g_open_loop.modulation_start;
    g_open_loop.electrical_frequency = g_open_loop.frequency_start;

    const uint32_t ramp_start_ms = mcl::time_ms();
    uint32_t last_ramp_update_ms = ramp_start_ms;

    timer_enable_interrupt(&tm);
    encoder_hold = true;
    timer_start(&tm);

    // Encoder bus
    serial::i2c bus(3, 10, 400'000, I2C2, GPIOB);
    svpwm_t calibration_svm{};
    calibration_svm.timer = &tm;
    calibrate_encoder(bus, calibration_svm);

    // Read the encoder at the final calibrated rotor position.
    encoder_read_and_update_angles(bus);
    // Start the open-loop electrical field from the
    // same electrical angle as the encoder.
    g_open_loop.angle = encoder.electrical_angle;
    // Discard any velocity-estimator state accumulated during calibration.
    reset_velocity_estimator();
    // Now allow TIM1 to advance the open-loop field.
    encoder_hold = false;
    uint32_t last_encoder_read_us = mcl::time_us();

    while (true) {
        // TIM1 update interrupt and SysTick can wake the processor.
        //__WFI();
        uint32_t now_ms = mcl::time_ms();
        // The ramp itself is very slow compared with the 20 kHz
        // PWM interrupt, so a 1 ms foreground update is sufficient.
        if ((uint32_t)(now_ms - last_ramp_update_ms) >= 1U) {
            float elapsed_s = (float)(now_ms - ramp_start_ms) * 0.001f;
            // Both values use exactly the same elapsed_s.
            // Therefore the voltage and frequency ramps are
            // synchronized.
            g_open_loop.modulation =
                ramp_linear(
                    g_open_loop.modulation_start,
                    g_open_loop.modulation_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            g_open_loop.electrical_frequency =
                ramp_linear(
                    g_open_loop.frequency_start,
                    g_open_loop.frequency_end,
                    g_open_loop.ramp_duration_s,
                    elapsed_s);
            last_ramp_update_ms = now_ms;
        }
        uint32_t now_us = mcl::time_us();
        if ((uint32_t)(now_us - last_encoder_read_us) >= ENCODER_READ_PERIOD_US) {
            last_encoder_read_us = now_us;
            encoder_read_and_update_angles(bus);
        }
        static uint32_t last_log_ms = 0;
        if ((uint32_t)(now_ms - last_log_ms) >= 10U) {
            float phase_error =
                g_open_loop.angle - encoder.electrical_angle;
            // wrap phase error to [-PI, PI].
            if (phase_error > PI)
                phase_error -= TWO_PI;
            else if (phase_error < -PI)
                phase_error += TWO_PI;
            LOG << "mod: " << g_open_loop.modulation
                << " ef_cmd: " << g_open_loop.electrical_frequency
                << " cmd_ea: " << g_open_loop.angle
                << " enc_ea: " << encoder.electrical_angle
                << " ph_err: " << phase_error
                << " ma: " << encoder.mechanical_angle
                << " wm: " << encoder.mechanical_velocity
                << " we: " << encoder.electrical_velocity;
            last_log_ms = now_ms;
        }
    }
    timer_stop(&tm);
}

#endif